//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWellWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class certificat
    {
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        public string NomCert { get; set; }
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        public string institut { get; set; }
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        public string annén { get; set; }
    
        public virtual medecin medecin { get; set; }
    }
}
