//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWellWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.diagnostique = new HashSet<diagnostique>();
            this.nootation = new HashSet<nootation>();
            this.rendezvous = new HashSet<rendezvous>();
            this.teleconsultation = new HashSet<teleconsultation>();
        }

        [RegularExpression("^([a-zA-Z]{2})([0-9]{5})$|^([a-zA-Z]{1})([0-9]{6})$", ErrorMessage = "le format de CIN est incorrecte")]
        [Required(ErrorMessage = "Ce est obligatoire")]
        public string CIN { get; set; }
        [Required(ErrorMessage = "Ce est obligatoire")]
        public string Nom { get; set; }
        [Required(ErrorMessage = "Ce est obligatoire")]
        public string Prenom { get; set; }
        [Required(ErrorMessage = "Ce est obligatoire")]
        public Nullable<System.DateTime> Date_naissance { get; set; }
        [RegularExpression(@"^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$", ErrorMessage = "le format de telephone saisit est incorrecte")]
        [Required(ErrorMessage = "Ce est obligatoire")]
        public string Tel { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Ce champ est obligatoire")]
        public string Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diagnostique> diagnostique { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nootation> nootation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rendezvous> rendezvous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teleconsultation> teleconsultation { get; set; }
    }
}
